version: '3'

services:

  main-config-server:
    build: ./main-config-server/
    ports:
      - 8888:8888
    networks:
      - main-network

  main-eureka-server:
    build: ./main-eureka-server/
    ports:
      - 8761:8761
    networks:
      - main-network

networks:
  main-network:
